# Generated by Django 6.0.5 on 2026-05-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_durable_pipeline'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_status_444bb6_idx',
            old_name='notification_status_next_attempt_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_tenant__56ab67_idx',
            old_name='notification_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_is_dead_373694_idx',
            old_name='notif_dead_status_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdeliveryattempt',
            new_name='notificatio_notific_292e6d_idx',
            old_name='notif_attempt_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationproviderhealth',
            new_name='notificatio_channel_62aef9_idx',
            old_name='provider_health_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='fallback_channel',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email'), ('webhook', 'Webhook'), ('panel', 'Panel'), ('log', 'Log')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='notification',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatching', 'Dispatching'), ('sent', 'Sent'), ('failed', 'Failed'), ('failed_fallback', 'Failed Fallback')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tenant_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationdeliveryattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationproviderhealth',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
