# Generated by Django 6.0.5 on 2026-05-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0003_runtime_protection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CircuitBreakerState',
        ),
        migrations.RemoveIndex(
            model_name='inflightrecord',
            name='inflight_lease_idx',
        ),
        migrations.RemoveConstraint(
            model_name='inflightrecord',
            name='uniq_inflight',
        ),
        migrations.DeleteModel(
            name='InFlightRecord',
        ),
        migrations.RemoveIndex(
            model_name='ratelimitbucket',
            name='rate_limit_window_idx',
        ),
        migrations.RemoveConstraint(
            model_name='ratelimitbucket',
            name='uniq_rate_limit_bucket',
        ),
        migrations.DeleteModel(
            name='RateLimitBucket',
        ),
        migrations.RenameIndex(
            model_name='agentcommand',
            new_name='agent_runti_status_08f190_idx',
            old_name='agent_cmd_status_available_idx',
        ),
        migrations.RenameIndex(
            model_name='agentcommand',
            new_name='agent_runti_target__3d9c41_idx',
            old_name='agent_cmd_target_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agentcommand',
            new_name='agent_runti_case_id_fe1bb2_idx',
            old_name='agent_cmd_case_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agentcommand',
            new_name='agent_runti_loop_si_67da7b_idx',
            old_name='agent_cmd_loop_signature_idx',
        ),
        migrations.RenameIndex(
            model_name='promptdefinition',
            new_name='agent_runti_agent_t_77e52d_idx',
            old_name='prompt_def_agent_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='promptdefinition',
            new_name='agent_runti_content_93f8fe_idx',
            old_name='prompt_def_content_hash_idx',
        ),
        migrations.AlterField(
            model_name='promptdefinition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('canary', 'Canary'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
