# Generated by Django 6.0.5 on 2026-05-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime', '0004_add_agent_execution_cost_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(max_length=128, unique=True)),
                ('agent_type', models.CharField(db_index=True, max_length=50)),
                ('prompt_version', models.IntegerField(default=1)),
                ('provider', models.CharField(default='local', max_length=50)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('tenant_id', models.CharField(db_index=True, default='docai_internal', max_length=100)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('lead_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('trigger', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.FloatField(default=0.0)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('llm_latency_ms', models.FloatField(default=0.0)),
                ('retry_count', models.IntegerField(default=0)),
                ('cache_hit', models.BooleanField(default=False)),
                ('status', models.CharField(default='success', max_length=30)),
                ('output_summary', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('feedback_quality', models.IntegerField(blank=True, help_text='1-5 quality rating', null=True)),
                ('feedback_useful', models.BooleanField(blank=True, help_text='Was the output useful?', null=True)),
                ('feedback_notes', models.TextField(blank=True, default='')),
                ('feedback_by', models.CharField(blank=True, default='', max_length=100)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_type', 'created_at'], name='agent_runti_agent_t_30755f_idx'), models.Index(fields=['tenant_id', 'created_at'], name='agent_runti_tenant__ce3dee_idx'), models.Index(fields=['lead_id'], name='agent_runti_lead_id_d83203_idx'), models.Index(fields=['status'], name='agent_runti_status_3d45c5_idx')],
            },
        ),
    ]
