# Generated by Django 6.0.5 on 2026-05-28 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERPConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, default='docai_internal', max_length=100)),
                ('provider', models.CharField(choices=[('omie', 'Omie'), ('bling', 'Bling'), ('totvs', 'TOTVS')], max_length=20)),
                ('name', models.CharField(help_text="Nome amigável da conexão (ex: 'Omie Produção')", max_length=200)),
                ('app_key', models.CharField(help_text='App Key / Client ID', max_length=255)),
                ('app_secret', models.CharField(help_text='App Secret / Client Secret', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_direction', models.CharField(choices=[('docai_to_erp', 'DocAI → ERP'), ('erp_to_docai', 'ERP → DocAI'), ('bidirectional', 'Bidirecional')], default='docai_to_erp', max_length=20)),
                ('auto_sync', models.BooleanField(default=False, help_text='Se ativo, sincroniza automaticamente após extração de documento.')),
                ('requires_approval', models.BooleanField(default=True, help_text='Se ativo, sync requer aprovação humana antes de executar.')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('is_circuit_open', models.BooleanField(default=False, help_text='Circuit breaker: se True, conexão está isolada por falhas.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Configurações extras do provider.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant_id', 'provider'], name='integration_tenant__35fc40_idx'), models.Index(fields=['is_active', 'is_circuit_open'], name='integration_is_acti_6c5b8f_idx')],
                'unique_together': {('tenant_id', 'provider', 'app_key')},
            },
        ),
        migrations.CreateModel(
            name='ERPFieldMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(help_text='Tipo de entidade (conta_pagar, cliente, etc)', max_length=50)),
                ('docai_field', models.CharField(help_text='Campo extraído pelo DocAI', max_length=100)),
                ('erp_field', models.CharField(help_text='Campo no ERP destino', max_length=100)),
                ('transform', models.CharField(blank=True, default='', help_text="Transformação: 'date_br', 'cents_to_decimal', 'cpf_cnpj_clean', etc", max_length=50)),
                ('default_value', models.CharField(blank=True, default='', max_length=200)),
                ('is_required', models.BooleanField(default=False)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='integrations.erpconnection')),
            ],
            options={
                'ordering': ['entity_type', 'docai_field'],
                'unique_together': {('connection', 'entity_type', 'docai_field')},
            },
        ),
        migrations.CreateModel(
            name='ERPSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(db_index=True, default='docai_internal', max_length=100)),
                ('entity_type', models.CharField(help_text='Tipo: conta_pagar, conta_receber, cliente, fornecedor, nf_entrada', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', help_text='ID interno do DocAI', max_length=100)),
                ('erp_entity_id', models.CharField(blank=True, default='', help_text='ID retornado pelo ERP', max_length=100)),
                ('direction', models.CharField(choices=[('docai_to_erp', 'DocAI → ERP'), ('erp_to_docai', 'ERP → DocAI'), ('bidirectional', 'Bidirecional')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('awaiting_approval', 'Aguardando Aprovação'), ('in_progress', 'Em Progresso'), ('success', 'Sucesso'), ('failed', 'Falhou'), ('retrying', 'Tentando Novamente')], default='pending', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(help_text='Chave para evitar duplicações', max_length=100, unique=True)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=100)),
                ('approval_id', models.CharField(blank=True, default='', help_text='ID da aprovação no gateway', max_length=100)),
                ('approved_by', models.CharField(blank=True, default='', max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.erpconnection')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='integration_tenant__55b564_idx'), models.Index(fields=['connection', 'entity_type'], name='integration_connect_b00960_idx'), models.Index(fields=['created_at'], name='integration_created_e6643b_idx')],
            },
        ),
    ]
