# Generated by Django 6.0.4 on 2026-05-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('facts', models.JSONField(blank=True, default=list)),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('pending_approvals', models.JSONField(blank=True, default=list)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to='orchestrator.case')),
            ],
            options={
                'indexes': [models.Index(fields=['case', 'created_at'], name='memory_memo_case_id_339eb0_idx')],
            },
        ),
    ]
