# Generated by Django 6.0.5 on 2026-05-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_case_embedding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='caseembedding',
            new_name='search_case_content_b82348_idx',
            old_name='search_caseemb_hash_idx',
        ),
    ]
