# Generated by Django 6.0.5 on 2026-05-13 14:31

import commercial.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orchestrator', '0003_rename_orch_evtin_tenant_processed_idx_orchestrato_tenant__74a293_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(default=commercial.models._new_lead_id, max_length=64, unique=True)),
                ('tenant_id', models.CharField(db_index=True, default='docai_internal', max_length=100)),
                ('source', models.CharField(choices=[('landing_page', 'Landing Page'), ('inbound_form', 'Inbound Form'), ('outbound', 'Outbound'), ('referral', 'Referral'), ('event', 'Event'), ('linkedin', 'LinkedIn'), ('meta_ads', 'Meta Ads'), ('google_ads', 'Google Ads'), ('partner', 'Partner'), ('manual', 'Manual'), ('import', 'CSV Import'), ('other', 'Other')], default='manual', max_length=40)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualifying', 'Qualifying'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('nurturing', 'Nurturing'), ('converted', 'Converted (Opportunity)')], db_index=True, default='new', max_length=30)),
                ('score', models.IntegerField(db_index=True, default=0, help_text='Lead score 0–100.')),
                ('contact_name', models.CharField(blank=True, default='', max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('company_size', models.CharField(blank=True, default='', max_length=50)),
                ('country', models.CharField(blank=True, default='BR', max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw payload received from the channel.')),
                ('icp_fit', models.JSONField(blank=True, default=dict, help_text='Per-criterion ICP fit assessment.')),
                ('qualification_reason', models.TextField(blank=True, default='')),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('consent_given', models.BooleanField(default=False, help_text='LGPD consent recorded at intake.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.ForeignKey(blank=True, help_text='Workflow case backing this lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_leads', to='orchestrator.case')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeadScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_before', models.IntegerField()),
                ('score_after', models.IntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='commercial.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_id', models.CharField(default=commercial.models._new_opportunity_id, max_length=64, unique=True)),
                ('tenant_id', models.CharField(db_index=True, default='docai_internal', max_length=100)),
                ('stage', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('demo_scheduled', 'Demo Scheduled'), ('demo_done', 'Demo Done'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=30)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('win_probability', models.FloatField(default=0.0)),
                ('owner_user_id', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_opportunities', to='orchestrator.case')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='commercial.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FollowUpDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_id', models.CharField(default=commercial.models._new_followup_id, max_length=64, unique=True)),
                ('tenant_id', models.CharField(db_index=True, default='docai_internal', max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending_approval', max_length=30)),
                ('approval_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('notification_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_by_agent', models.CharField(default='sales', max_length=80)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('lineage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='commercial.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='commercial.opportunity')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant_id', 'status'], name='commercial__tenant__5f10d2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant_id', 'score'], name='commercial__tenant__161876_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['tenant_id', 'stage'], name='commercial__tenant__19e3e7_idx'),
        ),
    ]
