# Generated by Django 6.0.5 on 2026-05-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_distributed_hardening'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approval',
            new_name='approvals_a_status_30864a_idx',
            old_name='approval_status_deadline_idx',
        ),
        migrations.RenameIndex(
            model_name='approval',
            new_name='approvals_a_tenant__c84ed1_idx',
            old_name='approval_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='approval',
            new_name='approvals_a_correla_7979d3_idx',
            old_name='approval_correlation_idx',
        ),
    ]
