# Generated by Django 6.0.3 on 2026-04-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_preference',
            field=models.CharField(choices=[('email', 'Apenas Email'), ('whatsapp', 'Apenas WhatsApp'), ('both', 'Email e WhatsApp'), ('none', 'Nenhum')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_expiration_days',
            field=models.PositiveIntegerField(default=7, help_text='Dias antes do vencimento para notificar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone para WhatsApp (com DDD)', max_length=20),
        ),
    ]
