# Generated by Django 6.0.2 on 2026-04-01 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_company_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('contract', 'Contrato'), ('invoice', 'Nota Fiscal'), ('balance', 'Balanço'), ('dre', 'DRE'), ('certificate', 'Certidão'), ('report', 'Relatório'), ('other', 'Outro')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Data de vencimento do documento', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reference_date',
            field=models.DateField(blank=True, help_text='Data de referência/competência do documento', null=True),
        ),
        migrations.CreateModel(
            name='ExpirationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('7_days', '7 dias antes'), ('3_days', '3 dias antes'), ('1_day', '1 dia antes'), ('expired', 'Vencido')], max_length=20)),
                ('sent_to', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiration_notifications', to='documents.document')),
            ],
            options={
                'unique_together': {('document', 'notification_type', 'sent_to')},
            },
        ),
        migrations.CreateModel(
            name='FinancialIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('receita_bruta', 'Receita Bruta'), ('receita_liquida', 'Receita Líquida'), ('custo', 'Custo dos Produtos/Serviços'), ('lucro_bruto', 'Lucro Bruto'), ('despesas_op', 'Despesas Operacionais'), ('ebitda', 'EBITDA'), ('lucro_op', 'Lucro Operacional'), ('lucro_liquido', 'Lucro Líquido'), ('ativo_total', 'Ativo Total'), ('passivo_total', 'Passivo Total'), ('patrimonio_liq', 'Patrimônio Líquido'), ('margem_bruta', 'Margem Bruta (%)'), ('margem_liquida', 'Margem Líquida (%)'), ('margem_ebitda', 'Margem EBITDA (%)')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('period', models.DateField(blank=True, help_text='Período de referência do indicador', null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_indicators', to='documents.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'indicator_type'], name='documents_f_documen_ad4b35_idx')],
                'unique_together': {('document', 'indicator_type', 'period')},
            },
        ),
    ]
