# Generated by Django 6.0.3 on 2026-04-01 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_document_type_document_expiration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[('multa', 'Multa/Penalidade'), ('reajuste', 'Reajuste/Correção'), ('rescisao', 'Rescisão'), ('vigencia', 'Vigência/Prazo'), ('renovacao', 'Renovação Automática'), ('confidencialidade', 'Confidencialidade'), ('garantia', 'Garantia'), ('pagamento', 'Condições de Pagamento'), ('responsabilidade', 'Responsabilidade/Obrigações'), ('foro', 'Foro/Jurisdição'), ('outro', 'Outra Cláusula Importante')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Texto completo da cláusula')),
                ('summary', models.TextField(blank=True, help_text='Resumo gerado pela IA')),
                ('risk_level', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto')], default='medium', max_length=10)),
                ('extracted_value', models.CharField(blank=True, help_text='Valor extraído (ex: 2% ao mês, 30 dias)', max_length=255)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='documents.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'clause_type'], name='documents_c_documen_bdbfaa_idx')],
            },
        ),
    ]
