# Generated by Django 6.0.4 on 2026-04-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_contractclause'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_metadata',
            field=models.JSONField(blank=True, help_text='Metadados extraídos automaticamente (NF, Certidão, etc.)', null=True),
        ),
    ]
