# Generated by Django 6.0.4 on 2026-05-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_ref', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('tenant_id', models.CharField(default='default', max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('new', 'New'), ('triage', 'Triage'), ('qualified', 'Qualified'), ('waiting_doc_sample', 'Waiting Doc Sample'), ('doc_sent_to_docai', 'Doc Sent To DocAI'), ('analysis_ready', 'Analysis Ready'), ('proposal_draft_ready', 'Proposal Draft Ready'), ('waiting_human_approval', 'Waiting Human Approval'), ('approved_to_send', 'Approved To Send'), ('followup_scheduled', 'Follow-up Scheduled'), ('won', 'Won'), ('lost', 'Lost'), ('blocked', 'Blocked'), ('failed', 'Failed'), ('closed', 'Closed')], default='new', max_length=50)),
                ('workflow_status', models.CharField(choices=[('running', 'Running'), ('waiting_approval', 'Waiting Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='running', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('correlation_id', models.CharField(db_index=True, max_length=100)),
                ('trace_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'state'], name='orchestrato_tenant__142862_idx'), models.Index(fields=['correlation_id'], name='orchestrato_correla_a4159d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(choices=[('lead.received', 'Lead Received'), ('lead.qualified', 'Lead Qualified'), ('document.sample.requested', 'Document Sample Requested'), ('document.sample.received', 'Document Sample Received'), ('docai.analysis.requested', 'DocAI Analysis Requested'), ('docai.analysis.completed', 'DocAI Analysis Completed'), ('proposal.draft.generated', 'Proposal Draft Generated'), ('approval.required', 'Approval Required'), ('approval.granted', 'Approval Granted'), ('approval.rejected', 'Approval Rejected'), ('workflow.transitioned', 'Workflow Transitioned'), ('workflow.failed', 'Workflow Failed')], max_length=80)),
                ('event_version', models.CharField(default='1.0', max_length=20)),
                ('source', models.CharField(max_length=120)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('correlation_id', models.CharField(db_index=True, max_length=100)),
                ('trace_id', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orchestrator.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('assignee_agent', models.CharField(blank=True, max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='orchestrator.case')),
            ],
        ),
        migrations.CreateModel(
            name='DLQEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('replayable', models.BooleanField(default=True)),
                ('payload', models.JSONField(default=dict)),
                ('trace_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlq_events', to='orchestrator.case')),
                ('original_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dlq_entries', to='orchestrator.caseevent')),
            ],
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['case', 'created_at'], name='orchestrato_case_id_39e56d_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['event_type'], name='orchestrato_event_t_80d673_idx'),
        ),
        migrations.AddIndex(
            model_name='casetask',
            index=models.Index(fields=['case', 'is_completed'], name='orchestrato_case_id_717fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='dlqevent',
            index=models.Index(fields=['case', 'created_at'], name='orchestrato_case_id_4ffb3b_idx'),
        ),
    ]
