# Generated by Django 6.0.5 on 2026-05-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_distributed_hardening'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventinbox',
            new_name='orchestrato_tenant__74a293_idx',
            old_name='orch_evtin_tenant_processed_idx',
        ),
        migrations.RenameIndex(
            model_name='eventinbox',
            new_name='orchestrato_event_t_54c0e8_idx',
            old_name='orch_evtin_event_type_idx',
        ),
        migrations.RenameIndex(
            model_name='eventoutbox',
            new_name='orchestrato_status_42be55_idx',
            old_name='orch_outbox_status_available_idx',
        ),
        migrations.RenameIndex(
            model_name='eventoutbox',
            new_name='orchestrato_tenant__cf3378_idx',
            old_name='orch_outbox_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='eventoutbox',
            new_name='orchestrato_correla_65e843_idx',
            old_name='orch_outbox_correlation_idx',
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='event_type',
            field=models.CharField(choices=[('lead.received', 'Lead Received'), ('lead.qualified', 'Lead Qualified'), ('lead.disqualified', 'Lead Disqualified'), ('lead.scored', 'Lead Scored'), ('opportunity.created', 'Opportunity Created'), ('opportunity.stage_changed', 'Opportunity Stage Changed'), ('followup.drafted', 'Follow-up Drafted'), ('followup.sent', 'Follow-up Sent'), ('demo.insight.generated', 'Demo Insight Generated'), ('executive.alert.raised', 'Executive Alert Raised'), ('document.sample.requested', 'Document Sample Requested'), ('document.sample.received', 'Document Sample Received'), ('docai.analysis.requested', 'DocAI Analysis Requested'), ('docai.analysis.completed', 'DocAI Analysis Completed'), ('proposal.draft.generated', 'Proposal Draft Generated'), ('approval.required', 'Approval Required'), ('approval.granted', 'Approval Granted'), ('approval.rejected', 'Approval Rejected'), ('workflow.transitioned', 'Workflow Transitioned'), ('workflow.failed', 'Workflow Failed')], max_length=80),
        ),
    ]
