# Generated by Django 6.0.4 on 2026-05-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('actor_type', models.CharField(default='system', max_length=50)),
                ('actor_id', models.CharField(blank=True, max_length=120)),
                ('trace_id', models.CharField(blank=True, max_length=100)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='orchestrator.case')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', 'created_at'], name='audit_audit_case_id_f32b2c_idx'), models.Index(fields=['trace_id'], name='audit_audit_trace_i_a4e590_idx')],
            },
        ),
    ]
